version: '3.5'
services:

    mongo:
        image: mongo:xenial
        container_name: mongo
        restart: always
        volumes:
            - ./mongodata:/data/db

    cms:
        image: matteljay/tightcms
        container_name: cms
        restart: always
        ports:
            - 80:80/tcp
        environment:
            EXPRESS_PORT: 80
            DB_HOST: mongo
            #DB_PORT: 27017
            #DB_USER:
            #DB_PASS:
            #DB_NAME: tightcms_content
            USER_PW_SALT: tightsalt
            JWT_SECRET: tightsecret
            #JWT_EXPIRE: 125h
        volumes:
            - ./uploads:/usr/src/app/public/uploads
        depends_on:
            - mongo

# EOF
